"""empty message

Revision ID: 2c469f49e75
Revises: 1cd9d2f6525
Create Date: 2014-11-15 20:32:30.667932

"""

# revision identifiers, used by Alembic.
revision = '2c469f49e75'
down_revision = '1cd9d2f6525'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
