"""Initial migration

Revision ID: 480758223d4
Revises: None
Create Date: 2014-11-08 12:41:27.693137

"""

# revision identifiers, used by Alembic.
revision = '480758223d4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
