"""empty message

Revision ID: bfdfc70076
Revises: None
Create Date: 2014-11-15 15:38:38.993222

"""

# revision identifiers, used by Alembic.
revision = 'bfdfc70076'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
